/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('ant-design-vue/es')['Input']
    IconChevronRight: typeof import('./src/components/icons/IconChevronRight.vue')['default']
    IconData: typeof import('./src/components/icons/IconData.vue')['default']
    IconDiary: typeof import('./src/components/icons/IconDiary.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconQuote: typeof import('./src/components/icons/IconQuote.vue')['default']
    IconRight: typeof import('./src/components/icons/IconChevronRight.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheComponent: typeof import('./src/components/TheComponent.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
