/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    copy: typeof import('./src/components/TheExpandPrenatalCard copy.vue')['default']
    Icon24: typeof import('./src/components/icons/Icon24.vue')['default']
    IconAfterMoon: typeof import('./src/components/icons/IconAfterMoon.vue')['default']
    IconCalendar: typeof import('./src/components/icons/IconCalendar.vue')['default']
    IconChanqianJiancha: typeof import('./src/components/icons/IconChanqianJiancha.vue')['default']
    IconChevronBottom: typeof import('./src/components/icons/IconChevronBottom.vue')['default']
    IconChevronLeft: typeof import('./src/components/icons/IconChevronLeft.vue')['default']
    IconChevronRight: typeof import('./src/components/icons/IconChevronRight.vue')['default']
    IconCircleCheck: typeof import('./src/components/icons/IconCircleCheck.vue')['default']
    IconData: typeof import('./src/components/icons/IconData.vue')['default']
    IconDiary: typeof import('./src/components/icons/IconDiary.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconMedal: typeof import('./src/components/icons/IconMedal.vue')['default']
    IconMenu: typeof import('./src/components/icons/IconMenu.vue')['default']
    IconNoon: typeof import('./src/components/icons/IconNoon.vue')['default']
    IconNotification: typeof import('./src/components/icons/IconNotification.vue')['default']
    IconParents: typeof import('./src/components/icons/IconParents.vue')['default']
    IconPencil: typeof import('./src/components/icons/IconPencil.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconPregnancy: typeof import('./src/components/icons/IconPregnancy.vue')['default']
    IconQuote: typeof import('./src/components/icons/IconQuote.vue')['default']
    IconRight: typeof import('./src/components/icons/IconRight.vue')['default']
    IconService: typeof import('./src/components/icons/IconService.vue')['default']
    IconSetting: typeof import('./src/components/icons/IconSetting.vue')['default']
    IconSettings: typeof import('./src/components/icons/IconSettings.vue')['default']
    IconSun: typeof import('./src/components/icons/IconSun.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBarChart: typeof import('./src/components/TheBarChart.vue')['default']
    TheCalendar: typeof import('./src/components/TheCalendar.vue')['default']
    TheExpandPrenatalCard: typeof import('./src/components/TheExpandPrenatalCard.vue')['default']
    TheExpandUltrasoundCard: typeof import('./src/components/TheExpandUltrasoundCard.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    ThePrenatalCard: typeof import('./src/components/ThePrenatalCard.vue')['default']
    TheProgressCircle: typeof import('./src/components/TheProgressCircle.vue')['default']
    TheUltrasoundCard: typeof import('./src/components/TheUltrasoundCard.vue')['default']
  }
}
