/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/data': RouteRecordInfo<'/data', '/data', Record<never, never>, Record<never, never>>,
    '/diary/': RouteRecordInfo<'/diary/', '/diary', Record<never, never>, Record<never, never>>,
    '/diary/all': RouteRecordInfo<'/diary/all', '/diary/all', Record<never, never>, Record<never, never>>,
    '/diary/prenatal/[id]': RouteRecordInfo<'/diary/prenatal/[id]', '/diary/prenatal/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/diary/ultrasound/[id]': RouteRecordInfo<'/diary/ultrasound/[id]', '/diary/ultrasound/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
    '/sub/': RouteRecordInfo<'/sub/', '/sub', Record<never, never>, Record<never, never>>,
  }
}
